### ISSUE TITLE
Removes attributes that contain code nodes

### ISSUE THREAD

**Issue by jescalan** [reshape/minify#10]
There's a small bug where reshape-minify will remove attributes that contain code nodes. That is, if you have an attribute that contains an expression as such:

```
div(class="{{ someLocal }}") hello!
```

It will be removed as if it were an empty attribute. This issue can be traced back to the [removeEmptyAttributes](https://github.com/reshape/minify/blob/master/lib/modules/emptyAttrs.js) module, which is not properly aware of code nodes.

To learn more about the reshape AST and different types of nodes, [check out the docs](https://github.com/reshape/reshape#reshape-ast)!

In order to fix this, I'd recommend first setting up a failing test, then diving into the code.

**Comment by mwickett** [comment]
I *think* this can be closed because of fcadd2e :)

**Comment by jescalan** [comment]
Whoo! 🎉
